version: '3.7'

services:
  gutendex:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "${DATABASE_USER}", "-d", "${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  gutendex-app:
    image: gutendex-app
    restart: always
    depends_on:
      - gutendex
    environment:
      DATABASE_HOST: gutendex
    networks:
      - backend
      - frontend  # Added frontend network
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html/static

    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    depends_on:
      - gutendex-app

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  postgres-data:
